### ISSUE TITLE
Does not work with Test::MockFile

### ISSUE THREAD

**Issue by EvanCarroll** [cpanel/Overload-FileCheck#16] opened 2020-06-03 23:30 UTC
The following test,

```
use Overload::FileCheck ();

# runs fine without this.
use Test::MockFile ();

Overload::FileCheck::mock_all_file_checks( sub {
    return Overload::FileCheck::FALLBACK_TO_REAL_OP();
} );

-e '/foo';
```

Will produce the somewhat cryptic error,

    -A is already mocked by Overload::FileCheck

**Comment by atoomic** [comment] 2020-06-04 16:44
Test::MockFile uses Overload::FileCheck under the hood...
Test::MockFile by design mocks all -X check using Overload::FileCheck.

You cannot mock -X a second time when using Test::MockFile.
IMO you should use one or the other.

Closing this case by design

**Closed by atoomic** 2020-06-04 16:44 UTC

**Comment by EvanCarroll** [comment] 2020-06-04 16:57
@atoomic So if a test is using `Test::MockFile` and we need to mock a file-exists test on a touchfile, we have to rewrite the whole test to use `Overload::FileCheck`?

**Comment by atoomic** [comment] 2020-06-04 18:26
no I would say just use Test::MockFile API to mock the file as existing or not when using Test::MockFile and you have the -X checks mocked for you

**Comment by toddr** [comment] 2020-06-04 18:28
Create the file in Test::Mock file and you've effectively done what you want. You either should be using Test::MockFile in a test file or Overload::FileCheck. NEVER both.
